[TAIPY]

[DATA_NODE.historical_temperature]

[DATA_NODE.date_to_forecast]

[DATA_NODE.predictions]

[TASK.predict]
function = "__main__.predict:function"
inputs = [ "historical_temperature:SECTION", "date_to_forecast:SECTION",]
outputs = [ "predictions:SECTION",]
skippable = "False:bool"

[SCENARIO.my_scenario]
tasks = [ "predict:SECTION",]
additional_data_nodes = []
frequency = "MONTHLY:FREQUENCY"

[SCENARIO.my_scenario.comparators]

[SCENARIO.my_scenario.sequences]
