name: Verify pyi
description: Verify automatic pyi file generation process
runs:
  using: "composite"
  steps:
    - name: Generate pyi
      shell: bash
      run: cp tools/gui/generate_pyi.py pyi_temp.py && pipenv run python pyi_temp.py && rm pyi_temp.py
    - name: Cleanup any untracked files
      shell: bash
      run: git clean -f
