name: Verify pyi
description: Verify automatic pyi file generation process
runs:
  using: "composite"
  steps:
    - name: install dependency
      shell: bash
      run: pipenv run pip install mypy black isort
    - name: Generate pyi
      shell: bash
      run: pipenv run python tools/gui/generate_pyi.py
    - name: Cleanup any untracked files
      shell: bash
      run: git clean -f
