name: 💡 Feature Request
description: Have any new idea or new feature for Taipy? Please suggest!
title: "<write a small description here>"
labels: ["✨New feature"]
body:
  - type: markdown
    attributes:
      value: |
        - Thank you for using Taipy and taking the time to suggest a new feature! 😄
        - Take a look at our template and try to add as much detail as possible.
        - If any heading is not applicable, please set it to `NA`.

  - type: textarea
    id: description_feature
    attributes:
      label: "Description"
      description: Please describe the lacking functionality that this issue would address.
      placeholder: A detailed description of the new feature request.
    validations:
      required: true

  - type: textarea
    id: feature_solution_proposed
    attributes:
      label: "Solution Proposed"
      description: A precise description of how you would like to see this functionality implemented.
      placeholder: Including any relevant materials such as sketches, wireframes, or flowcharts to illustrate your proposal is highly welcomed.

  - type: textarea
    id: feature_impact_solution
    attributes:
      label: "Impact of Solution"
      description: What impact could that feature have on the rest of the product, and should be taken special care of?
      placeholder: Including any relevant info to understand the impact of solution on the rest of the product.

  - type: textarea
    id: additional_context_feature
    attributes:
      label: "Additional Context"
      description: If you have any additional context or information that may help us to implement this feature, please provide it here. (workaround, third-party...)
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: Do not edit the text area below.
      value: |
        - [ ] If applicable, a new demo code is provided to show the new feature in action.
        - [ ] Integration tests exhibiting how the functionality works are added.
        - [ ] Any new code is covered by a unit tested.
        - [ ] Check code coverage is at least 90%.
        - [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

  - type: checkboxes
    id: terms_checklist_feature
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md).
      options:
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false

  - type: markdown
    attributes:
      value: Thank you for taking the time to suggest a feature request! 😄
