name: Other
description: Use this for any other question or issue. Please do not create blank issues.
title: "[OTHER] <write a small description here>"
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        - Thank you for using Taipy and taking the time to submit this issue! 😄 
        - This is for discussion or any questions you may have.

  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share or ask?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true

  - type: checkboxes
    id: terms_checklist_discussion
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md).
      options:
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
          
  - type: markdown
    attributes:
      value: Thank you for taking the time to report the issue! 😄
