name: 🔧 Refactor Code/Feature Improvement
description: Use this form for code refactoring tasks or existing feature improvement.
title: "[Refactor] <write a small description here>"
labels: ["📈 Improvement"]
body:
  - type: markdown
    attributes:
      value: |
        - Thank you for using Taipy and taking the time to suggest feature improvements! 😄

  - type: textarea
    id: refactor_description
    attributes:
      label: "Description"
      description: "Describe what improvements can be made(performance, API...) in the codebase without introducing breaking changes."
    validations:
      required: true

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      options:
        - label: "Ensure new code is unit tested, and check code coverage is at least 90%."
          required: false
        - label: "Propagate any change on the demos and run all of them to ensure there is no breaking change."
          required: false
        - label: "Ensure any change is well documented."
          required: false

  - type: checkboxes
    id: terms_checklist_refactor
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Avaiga/taipy/blob/develop/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md).
      options:
        - label: "I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+)."
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
          
  - type: markdown
    attributes:
      value: Thank you for taking the time to report the issue! 😄
