"""Top-level package for Taipy Gui.

The Taipy Gui package is a module of Taipy that provides
User Interface generation based on page templates.<br/>
The pages are generated by a Web server that allows Web clients
to connect, display and interact with the page content through
visual elements.
"""

__author__ = """Avaiga"""
__email__ = "taipy.dev@avaiga.com"
__version__ = "1.0.0.dev"
