/*
 * Copyright 2021-2025 Avaiga Private Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
/*
 * This script adds the license header to the generated TypeScript declaration file.
 */

const fs = require("node:fs");
const path = require("node:path");

const targetPathArg = process.argv[2];
if (!targetPathArg) {
    console.error("Usage: node scripts/add-header.js <target-file>");
    process.exit(1);
}

// Read header from the <project-root>/.license-header file 
const projectRoot = path.resolve(__dirname, "../../..");
const headerTemplatePath = path.join(projectRoot, ".license-header");
if (!fs.existsSync(headerTemplatePath)) {
    console.error(`Error: Header template file "${headerTemplatePath}" does not exist.`);
    process.exit(1);
}
const headerText = `/*\n${fs.readFileSync(headerTemplatePath, "utf8").replace(/\r\n/g, "\n").trimEnd().split("\n").map((line) => (line ? ` * ${line}` : " *")).join("\n")}\n */\n\n`;
// Read the target file content
const targetPath = path.resolve(path.resolve(__dirname, ".."), targetPathArg);
if (!fs.existsSync(targetPath)) {
    console.error(`Error: Target file "${targetPath}" does not exist.`);
    process.exit(1);
}
let content = fs.readFileSync(targetPath, "utf8").replace(/^\uFEFF/, "");
// Replace the dts-bundle-generator banner with the header text
content = content.replace(/^\/\/ Generated by dts-bundle-generator[^\n]*\n+/, "");
content = content.replace(/^\/\*[\s\S]*?\*\/\s*/, "");
// Replace single quotes with double quotes in import statements
content = content.replace(/(^\s*import\s+\{[^}]*\}\s+from\s+)'([^']*)';/gm, '$1"$2";');

fs.writeFileSync(targetPath, headerText + content, "utf8");
