name: Generate config.pyi

on:
  pull_request:
    branches: [ develop, dev/*, release/* ]

jobs:
  generate-pyi:
    timeout-minutes: 20
    strategy:
      matrix:
        python-versions: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Clone taipy-core
        run: git clone --single-branch --branch ${{ github.base_ref }} https://github.com/Avaiga/taipy-core.git
      - name: Generate config.pyi
        run: python stubs/generate_pyi.py
      - name: Remove taipy-core folder
        run: rm -fr taipy-core/
      - uses: stefanzweifel/git-auto-commit-action@v4
