name: Build and release one taipy package

on:
  workflow_dispatch:
    inputs:
      target_package:
        description: "Package name"
        required: true
        type: choice
        options:
          - gui
          - common
          - core
          - rest
          - templates
          - taipy
      target_version:
        description: "Package version"
        required: true
      release_type:
        description: "Release type"
        required: true
        type: choice
        options:
          - dev
          - production
        default: "dev"
      sub_packages_location:
        description: "Dependencies location"
        required: true
        type: choice
        options:
          - GitHub
          - Pypi
        default: "GitHub"

env:
  NODE_OPTIONS: --max-old-space-size=4096

permissions:
  contents: write

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
        common_VERSION: ${{ steps.version-setup.outputs.common_VERSION }}
        core_VERSION: ${{ steps.version-setup.outputs.core_VERSION }}
        gui_VERSION: ${{ steps.version-setup.outputs.gui_VERSION }}
        rest_VERSION: ${{ steps.version-setup.outputs.rest_VERSION }}
        templates_VERSION: ${{ steps.version-setup.outputs.templates_VERSION }}
        taipy_VERSION: ${{ steps.version-setup.outputs.taipy_VERSION }}
        LATEST_TAIPY_VERSION: ${{ steps.version-setup.outputs.LATEST_TAIPY_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Install mandatory Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check package version
        run: |
          python tools/release/check_package_version.py \
          ${{ github.event.inputs.target_package }} \
          ${{ github.event.inputs.target_version }}

      - name: Setup Version
        id: version-setup
        run: |
          python tools/release/fetch_latest_versions.py \
          ${{ github.event.inputs.target_package }} \
          ${{ github.event.inputs.target_version }} \
          ${{ github.event.inputs.release_type }} \
          ${{ github.event.inputs.sub_packages_location }}  \
          ${{ github.repository }} >>$GITHUB_OUTPUT

      - name: Verify versions
        run: |
          echo 'common' version: ${{ steps.version-setup.outputs.common_VERSION }}
          echo 'core' version: ${{ steps.version-setup.outputs.core_VERSION }}
          echo 'gui' version: ${{ steps.version-setup.outputs.gui_VERSION }}
          echo 'rest' version: ${{ steps.version-setup.outputs.rest_VERSION }}
          echo 'templates' version: ${{ steps.version-setup.outputs.templates_VERSION }}
          echo 'taipy' version: ${{ steps.version-setup.outputs.taipy_VERSION }}
          echo Latest 'taipy' version: ${{ steps.version-setup.outputs.LATEST_TAIPY_VERSION }}

  build-and-release-package:
    needs: fetch-versions
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract commit hash
        id: extract_hash
        shell: bash
        run: echo "HASH=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Install mandatory Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set build variables for ${{ github.event.inputs.target_package }} ${{ github.event.inputs.target_version }}
        id: set-variables
        shell: bash
        run: |
          echo "package_version=${{ github.event.inputs.target_version }}" >> $GITHUB_OUTPUT
          if [ "${{ github.event.inputs.target_package }}" == "taipy" ]; then
            echo "release_name=${{ github.event.inputs.target_version }}" >> $GITHUB_OUTPUT
            echo "tar_path=./dist/${{ github.event.repository.name }}-${{ github.event.inputs.target_version }}.tar.gz" >> $GITHUB_OUTPUT
          else
            echo "release_name=${{ github.event.inputs.target_version }}-${{ github.event.inputs.target_package }}" >> $GITHUB_OUTPUT
            echo "tar_path=./dist/${{ github.event.repository.name }}-${{ github.event.inputs.target_package }}-${{ github.event.inputs.target_version }}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Update setup.requirements.txt
        run: |
          python tools/release/update_setup_requirements.py ${{ github.event.inputs.target_package }} \
            ${{ needs.fetch-versions.outputs.common_VERSION }} \
            ${{ needs.fetch-versions.outputs.core_VERSION }} \
            ${{ needs.fetch-versions.outputs.gui_VERSION }} \
            ${{ needs.fetch-versions.outputs.rest_VERSION }} \
            ${{ needs.fetch-versions.outputs.templates_VERSION }} \
            ${{ github.event.inputs.sub_packages_location }} \
            ${{ github.repository }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel "pipenv<2025.0.0" mypy black isort

      - name: Install GUI dependencies
        if: ${{ github.event.inputs.target_package == 'gui' || github.event.inputs.target_package == 'taipy' }}
        run: |
          pipenv install --dev

      - name: Generate GUI pyi file
        if: github.event.inputs.target_package == 'gui'
        run: |
          pipenv run python tools/gui/generate_pyi.py

      - name: Build Taipy GUI front-end
        if: ${{ github.event.inputs.target_package == 'gui' || github.event.inputs.target_package == 'taipy' }}
        run: |
          python tools/frontend/bundle_build.py gui

      - name: Build Taipy front-end
        if: ${{ github.event.inputs.target_package == 'taipy' }}
        run: |
          python tools/frontend/bundle_build.py taipy

      - name: Build Package Structure
        run: |
          python tools/release/build_package_structure.py ${{ github.event.inputs.target_package }}

      - name: Build package
        working-directory: "build_${{ github.event.inputs.target_package }}"
        run: |
          python -m build
          for file in ./dist/*; do mv "$file" "${file//_/-}"; done

      - name: Create tag and release
        working-directory: "build_${{ github.event.inputs.target_package }}"
        run: |
          if [ "${{ github.event.inputs.release_type }}" == "dev" ]; then
            gh release create ${{ steps.set-variables.outputs.release_name }} ${{ steps.set-variables.outputs.tar_path }} --target ${{ steps.extract_hash.outputs.HASH }} --prerelease --title ${{ steps.set-variables.outputs.release_name }} --notes "Dev Release ${{ steps.set-variables.outputs.release_name }}"
          else
            gh release create ${{ steps.set-variables.outputs.release_name }} ${{ steps.set-variables.outputs.tar_path }} --target ${{ steps.extract_hash.outputs.HASH }} --title ${{ steps.set-variables.outputs.release_name }} --notes "Release ${{ steps.set-variables.outputs.release_name }}"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure the latest 'taipy' production release is marked as *latest* no matter what
        run: |
          gh release edit ${{ needs.fetch-versions.outputs.LATEST_TAIPY_VERSION }} --latest
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
