name: Cleanup Old Pre-Releases

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      version:
        description: "Taipy version to clean up without extension. Ex: 3.2.1 cleans up all dev releases 3.2.1.devX"
        required: true
      dry_run:
        description: "Perform a dry run without actually deleting any releases (default: True)"
        required: true
        type: choice
        options:
          - True
          - False
        default: "True"
      extension:
        description: "Which extension to clean up. (default: dev)"
        default: "dev"

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Display inputs
        run: |
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Dry run: ${{ github.event.inputs.dry_run }}"
          echo "Extension: ${{ github.event.inputs.extension }}"

      - name: Validate version
        run: |
          version="${{ github.event.inputs.version }}"
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format: '$version' - <M>.<m>.<p> is mandatory."
            exit 1
          fi
          echo "✅ Valid target version: $version"

      - name: Install mandatory Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Cleanup old dev releases
        id: cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/release/cleanup_dev_releases.py \
            --version ${{ github.event.inputs.version }} \
            --dry_run ${{ github.event.inputs.dry_run }} \
            --extension ${{ github.event.inputs.extension }}
