name: Partial Tests Workflow

on:
  workflow_call:

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags:  "--ignore-missing-imports --implicit-optional --disable-error-code attr-defined --no-namespace-packages --exclude (taipy/templates/|tools/|doc/gui/examples/.*/builder.py|taipy/common/config/config.pyi) --follow-imports skip --disable-error-code import-untyped"

      - uses: chartboost/ruff-action@v1
        with:
          src: './taipy ./tests'
  tests:
    needs: linter
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            common:
              - 'taipy/common/**'
            core:
              - 'taipy/core/**'
            gui:
              - 'taipy/gui/**'
              - 'frontend/taipy-gui/**'
            gui-core:
              - 'taipy/gui_core/**'
            rest:
              - 'taipy/rest/**'
            templates:
              - 'taipy/templates/**'

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pipenv'
          cache-dependency-path: 'Pipfile'
      - name: Install Setuptools and wheel
        run: pip install --upgrade "setuptools<80.0.0" wheel

      - name: Install pipenv
        run: pip install pipenv --upgrade

      - name: Install Dependencies
        run: pipenv install --dev --python=${{ matrix.python-version }}

      - name: Setup LibMagic (MacOS)
        if: matrix.os == 'macos-13'
        run: brew install libmagic

      - name: Setup Node
        if: steps.changes.outputs.gui == 'true' || steps.changes.outputs.gui-core == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
