name: Enterprise Secret Scanning

on:
  push:
    branches: [ develop, dev/*, release/* ]
  pull_request:
    branches: [ develop, dev/*, release/* ]

jobs:
  trufflehog:
    name: TruffleHog Secrets Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Must fetch all history to scan for leaked secrets in commits

      - name: Scan Pipeline
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
